# Generated by Django 4.1.3 on 2022-11-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_created_at_user_session_token_user_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="session_token",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
